<template>
      <!--prikaz podataka o pojedinom oglasu kao komponente -->
      <div class="card text-center">
        <div class="card-header text-left" >
           <strong >{{ info.imepoduzeca }}</strong>
          
        </div>
        <div class="card-body">
          <img class="card-img-top" :src="info.url" alt="">
        </div>
        <div class="card-footer text-left">
          <div v-if="!showcomments" > <button class="btn btn-primary" type="submit" style="position:relative;left:40%;">Detalji</button> </div>

          <div v-if="showcomments">
            <strong> Ime poduzeća: </strong> {{info.imepoduzeca}}
            <br>
            <strong> Oib: </strong> {{info.oib}}
            <br>
            <strong> Djelatnost: </strong> {{info.djelatnost}}
            <br>
            <strong> Županija: </strong> {{info.zupanija}}
            <br>
            <strong> Opis: </strong> {{info.opis}}
            <br>
            <strong> Kontakt: </strong> {{info.kontakt}}
            <br>
             Oglas postavljen: {{timeAgo}} <br> by: {{info.email}}
            <br>
            <div class="comments list-group">
              <a :key="c.posted_at" v-for="c in comments" href="#" class="animate list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <small>{{ formatTime(c.posted_at) }} by {{ c.email }} </small>
                </div>
                <small>{{ c.comment }}</small>
              </a>
            </div>

            <form @submit.prevent="postComment" class="form-inline mb-5">
              <div class="form-group">
                <input v-model="newComment" type="text" class="form-control" id="imageUrl" placeholder="Komentiraj...">
              </div>
              <button type="submit" class="btn btn-primary mt-2">Komentiraj</button>
            </form>
          </div>

        </div>
      </div>

</template>

<script>
import moment from 'moment'
import store from '@/store.js'

export default {
  props: [ "info", "showcomments"],
  data () {
    return {
      global: store,
      newComment: "",
      comments: [],
      
    }
  },

  mounted() {
    //prikaz komentara ukoliko ima promjena
    if (this.showcomments) {
     db.collection("posts").doc(this.info.id).collection("comments").onSnapshot(snapshot => {
        snapshot.docChanges().forEach(change => {
          
          if (change.type === "added") {
            let comment = change.doc.data();
            comment.isNew = true;
            this.comments.unshift(comment)
          }
        })
     })
    }
  },
  methods: {
    //vraca vrijeme 
    formatTime(t) {
      return moment(t.posted_at).fromNow()
    },

    getinfo(){
      


    },
    //dodavanje komentara u kolekciju posts za pojedini oglas i stvara podkolekciju comments (ukoliko ih nema) i tamo dodaje komentar o oglasu
    postComment() {
      if (this.newComment) {
        db.collection("posts")
          .doc(this.info.id)
            .collection("comments")
            .add({ email: this.global.userEmail, comment: this.newComment, posted_at: Date.now() })
              .then(result => {
                
                this.newComment = "";
              })
              .catch(e => {
                console.error(e)
              })
      }
    }
  },
  computed: {
    //vraca vrijeme kad je oglas postavljen
    timeAgo () {
      return moment(this.info.posted_at).fromNow()
    }
  }
}
</script>

<style>
  .card {
    margin: 10px;
    margin-left:0px;
    background-image: linear-gradient(to bottom right,  #d9ffff, #ebadff);
    max-width: 70%;
    opacity:0.8;
  }
  .card:hover{
    opacity:1;
  }
  .comments {
    margin: 20px 0
  }

  .btn-primary{
    background-color: transparent;
    border: 2px solid white;
    border-radius: 30px;
    color: black;
  }
  .btn-primary:hover{
    background-color: transparent;
    border-color: rgb(25, 138, 245);
    color:rgb(25, 138, 245);
  }

  
  /* ----------------------------------------------
  * Generated by Animista on 2020-1-3 19:19:35
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */
  @-webkit-keyframes fade-in-fwd{0%{-webkit-transform:translateZ(-80px);transform:translateZ(-80px);opacity:0}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}@keyframes fade-in-fwd{0%{-webkit-transform:translateZ(-80px);transform:translateZ(-80px);opacity:0}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}
  .animate{-webkit-animation:fade-in-fwd 1s cubic-bezier(.39,.575,.565,1.000) both;animation:fade-in-fwd 1s cubic-bezier(.39,.575,.565,1.000) both}

</style>